import { dist, round6 } from './geometry.js';
import { buildScene, SILK_W } from './scene.js';

/* ------------------------------------------------------------------ Gerber */

const MM = (v) => Math.round(v * 1e6);
const num = (v) => v.toFixed(6);

class Gerber {
  constructor(doc, fn, side) {
    this.h = doc.board.h;
    this.aps = new Map();
    this.body = [];
    this.head = [
      'G04 Generated by BreadBai PCB*',
      '%MOMM*%', '%FSLAX46Y46*%',
      `%TF.FileFunction,${fn}*%`, '%TF.FilePolarity,Positive*%',
    ];
    if (side) this.head.push(`%TF.Part,Single*%`);
    this.cur = null;
    this.next = 10;
  }
  X(x) { return `X${MM(x)}`; }
  Y(y) { return `Y${MM(this.h - y)}`; }
  aperture(spec) {
    if (!this.aps.has(spec)) this.aps.set(spec, this.next++);
    const code = this.aps.get(spec);
    if (this.cur !== code) { this.body.push(`D${code}*`); this.cur = code; }
  }
  flashC(x, y, d) { this.aperture(`C,${num(d)}`); this.body.push(`${this.X(x)}${this.Y(y)}D03*`); }
  flashR(x, y, w, h) { this.aperture(`R,${num(w)}X${num(h)}`); this.body.push(`${this.X(x)}${this.Y(y)}D03*`); }
  flashO(x, y, w, h) { this.aperture(`O,${num(w)}X${num(h)}`); this.body.push(`${this.X(x)}${this.Y(y)}D03*`); }
  draw(x1, y1, x2, y2, w) {
    this.aperture(`C,${num(w)}`);
    this.body.push(`${this.X(x1)}${this.Y(y1)}D02*`, `${this.X(x2)}${this.Y(y2)}D01*`);
  }
  circle(cx, cy, r, w) {
    this.aperture(`C,${num(w)}`);
    this.body.push('G75*', `${this.X(cx + r)}${this.Y(cy)}D02*`, 'G03*',
      `${this.X(cx + r)}${this.Y(cy)}I${MM(-r)}J0D01*`, 'G01*');
  }
  raw(line) { this.body.push(line); }
  toString() {
    const defs = [...this.aps].map(([spec, code]) => `%ADD${code}${spec}*%`);
    return [...this.head, ...defs, '%LPD*%', 'G01*', ...this.body, 'M02*', ''].join('\n');
  }
}

function flashPad(g, p, grow = 0) {
  const w = p.w + grow * 2, h = p.h + grow * 2;
  if (p.shape === 'rect') g.flashR(p.x, p.y, w, h);
  else if (Math.abs(p.w - p.h) < 1e-6) g.flashC(p.x, p.y, w);
  else g.flashO(p.x, p.y, w, h);
}

export function gerberCopper(doc, layer) {
  const g = new Gerber(doc, layer === 'top' ? 'Copper,L1,Top' : 'Copper,L2,Bot');
  const scene = buildScene(doc);
  for (const t of scene.tracks[layer]) g.draw(t.a.x, t.a.y, t.b.x, t.b.y, t.width);
  for (const p of scene.pads) flashPad(g, p);
  for (const v of scene.vias) g.flashC(v.x, v.y, v.dia);
  return g.toString();
}

export function gerberMask(doc, layer) {
  const g = new Gerber(doc, layer === 'top' ? 'Soldermask,Top' : 'Soldermask,Bot');
  const scene = buildScene(doc);
  const m = doc.rules.maskExpansion;
  for (const p of scene.pads) flashPad(g, p, m);
  for (const v of scene.vias) g.flashC(v.x, v.y, v.dia + m * 2);
  return g.toString();
}

export function gerberSilk(doc, side) {
  const g = new Gerber(doc, side === 'top' ? 'Legend,Top' : 'Legend,Bot');
  for (const s of buildScene(doc).silk[side]) {
    if (s.k === 'line') g.draw(s.x1, s.y1, s.x2, s.y2, SILK_W);
    else g.circle(s.x, s.y, s.r, SILK_W);
  }
  return g.toString();
}

export function gerberOutline(doc) {
  const { w, h } = doc.board;
  const r = Math.max(0, Math.min(doc.board.r ?? 0, w / 2, h / 2));
  const g = new Gerber(doc, 'Profile,NP');
  g.aperture(`C,${num(0.1)}`);
  const at = (x, y) => `${g.X(x)}${g.Y(y)}`;
  // Gerber y is flipped relative to the editor, so this path runs anticlockwise in Gerber space.
  g.raw('G75*');
  g.raw(`${at(r, h)}D02*`);
  g.raw('G01*'); g.raw(`${at(w - r, h)}D01*`);
  if (r > 0) { g.raw('G03*'); g.raw(`${at(w, h - r)}I0J${MM(r)}D01*`); g.raw('G01*'); }
  g.raw(`${at(w, r)}D01*`);
  if (r > 0) { g.raw('G03*'); g.raw(`${at(w - r, 0)}I${MM(-r)}J0D01*`); g.raw('G01*'); }
  g.raw(`${at(r, 0)}D01*`);
  if (r > 0) { g.raw('G03*'); g.raw(`${at(0, r)}I0J${MM(-r)}D01*`); g.raw('G01*'); }
  g.raw(`${at(0, h - r)}D01*`);
  if (r > 0) { g.raw('G03*'); g.raw(`${at(r, h)}I${MM(r)}J0D01*`); g.raw('G01*'); }
  return g.toString();
}

/* ---------------------------------------------------------------- Excellon */

export function excellon(doc) {
  const scene = buildScene(doc);
  const holes = [
    ...scene.pads.filter((p) => p.drill > 0).map((p) => ({ x: p.x, y: p.y, d: p.drill })),
    ...scene.vias.map((v) => ({ x: v.x, y: v.y, d: v.drill })),
  ];
  const sizes = [...new Set(holes.map((h) => round6(h.d)))].sort((a, b) => a - b);
  const out = ['M48', '; Generated by BreadBai PCB', 'FMAT,2', 'METRIC,TZ'];
  sizes.forEach((d, i) => out.push(`T${i + 1}C${d.toFixed(3)}`));
  out.push('%', 'G90', 'G05');
  sizes.forEach((d, i) => {
    out.push(`T${i + 1}`);
    for (const h of holes.filter((q) => round6(q.d) === d)) out.push(`X${h.x.toFixed(3)}Y${(doc.board.h - h.y).toFixed(3)}`);
  });
  out.push('T0', 'M30', '');
  return out.join('\n');
}

/* --------------------------------------------------------------------- SVG */

export const COLORS = {
  technical: { bg: '#15171b', board: '#1d2026', edge: '#c8c8d0', top: '#d2453d', bottom: '#3b82f6', silkTop: '#e8e8ee', silkBottom: '#8fb4ff', pad: '#f0c674', hole: '#0b0c0e' },
  realistic: { bg: '#0d0d0f', board: '#0e5a34', edge: '#e6d9a8', top: '#d8b45c', bottom: '#b89a4f', silkTop: '#f4f4f0', silkBottom: '#d9e3ef', pad: '#e8cf85', hole: '#0a0a0a' },
};

function boardPath({ w, h, r }) {
  const k = Math.max(0, Math.min(r ?? 0, w / 2, h / 2));
  if (!k) return `M0 0H${w}V${h}H0Z`;
  return `M${k} 0H${w - k}A${k} ${k} 0 0 1 ${w} ${k}V${h - k}A${k} ${k} 0 0 1 ${w - k} ${h}H${k}A${k} ${k} 0 0 1 0 ${h - k}V${k}A${k} ${k} 0 0 1 ${k} 0Z`;
}

export function svgString(doc, { side = 'top', style = 'realistic' } = {}) {
  const c = COLORS[style];
  const { w, h } = doc.board;
  const scene = buildScene(doc);
  const order = side === 'top' ? ['bottom', 'top'] : ['top', 'bottom'];
  const seg = (a, b, wd, col) => `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${col}" stroke-width="${wd}" stroke-linecap="round"/>`;
  const out = [`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1 -1 ${w + 2} ${h + 2}" width="${(w + 2) * 8}" height="${(h + 2) * 8}">`,
    `<rect x="-1" y="-1" width="${w + 2}" height="${h + 2}" fill="${c.bg}"/>`];
  out.push(`<g${side === 'bottom' ? ` transform="translate(${w} 0) scale(-1 1)"` : ''}>`);
  out.push(`<path d="${boardPath(doc.board)}" fill="${c.board}" stroke="${c.edge}" stroke-width="0.15"/>`);
  for (const layer of order) {
    for (const t of scene.tracks[layer]) out.push(seg(t.a, t.b, t.width, c[layer]));
  }
  for (const p of scene.pads) {
    if (p.shape === 'rect') out.push(`<rect x="${p.x - p.w / 2}" y="${p.y - p.h / 2}" width="${p.w}" height="${p.h}" fill="${c.pad}"/>`);
    else if (Math.abs(p.w - p.h) < 1e-6) out.push(`<circle cx="${p.x}" cy="${p.y}" r="${p.w / 2}" fill="${c.pad}"/>`);
    else out.push(`<rect x="${p.x - p.w / 2}" y="${p.y - p.h / 2}" width="${p.w}" height="${p.h}" rx="${Math.min(p.w, p.h) / 2}" fill="${c.pad}"/>`);
    if (p.drill > 0) out.push(`<circle cx="${p.x}" cy="${p.y}" r="${p.drill / 2}" fill="${c.hole}"/>`);
  }
  for (const v of scene.vias) out.push(`<circle cx="${v.x}" cy="${v.y}" r="${v.dia / 2}" fill="${c.pad}"/><circle cx="${v.x}" cy="${v.y}" r="${v.drill / 2}" fill="${c.hole}"/>`);
  const silk = side === 'top' ? scene.silk.top : scene.silk.bottom;
  const col = side === 'top' ? c.silkTop : c.silkBottom;
  for (const s of silk) {
    if (s.k === 'line') out.push(seg({ x: s.x1, y: s.y1 }, { x: s.x2, y: s.y2 }, SILK_W, col));
    else out.push(`<circle cx="${s.x}" cy="${s.y}" r="${s.r}" fill="none" stroke="${col}" stroke-width="${SILK_W}"/>`);
  }
  out.push('</g></svg>');
  return out.join('\n');
}

/* --------------------------------------------------------------------- ZIP */

const CRC = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; }
  return t;
})();
const crc32 = (bytes) => { let c = 0xffffffff; for (const b of bytes) c = CRC[(c ^ b) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };

/** Minimal "store" (uncompressed) ZIP writer — enough for a Gerber pack. */
export function zipStore(files) {
  const enc = new TextEncoder();
  const chunks = [], central = [];
  let offset = 0;
  const u16 = (v) => [v & 255, (v >> 8) & 255];
  const u32 = (v) => [v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >>> 24) & 255];
  for (const f of files) {
    const name = enc.encode(f.name), data = enc.encode(f.data), crc = crc32(data);
    const head = [...u32(0x04034b50), ...u16(20), ...u16(0x0800), ...u16(0), ...u16(0), ...u16(0x21),
      ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0)];
    chunks.push(Uint8Array.from(head), name, data);
    central.push(Uint8Array.from([...u32(0x02014b50), ...u16(20), ...u16(20), ...u16(0x0800), ...u16(0), ...u16(0), ...u16(0x21),
      ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0), ...u16(0), ...u16(0), ...u16(0), ...u32(0), ...u32(offset)]), name);
    offset += head.length + name.length + data.length;
  }
  const cdSize = central.reduce((s, c) => s + c.length, 0);
  const end = Uint8Array.from([...u32(0x06054b50), ...u16(0), ...u16(0), ...u16(files.length), ...u16(files.length), ...u32(cdSize), ...u32(offset), ...u16(0)]);
  const all = [...chunks, ...central, end];
  const out = new Uint8Array(all.reduce((s, c) => s + c.length, 0));
  let p = 0;
  for (const c of all) { out.set(c, p); p += c.length; }
  return out;
}

export function fabPackage(doc, name = 'board') {
  return [
    { name: `${name}-F_Cu.gbr`, data: gerberCopper(doc, 'top') },
    { name: `${name}-B_Cu.gbr`, data: gerberCopper(doc, 'bottom') },
    { name: `${name}-F_Mask.gbr`, data: gerberMask(doc, 'top') },
    { name: `${name}-B_Mask.gbr`, data: gerberMask(doc, 'bottom') },
    { name: `${name}-F_Silkscreen.gbr`, data: gerberSilk(doc, 'top') },
    { name: `${name}-B_Silkscreen.gbr`, data: gerberSilk(doc, 'bottom') },
    { name: `${name}-Edge_Cuts.gbr`, data: gerberOutline(doc) },
    { name: `${name}.drl`, data: excellon(doc) },
  ];
}

export const totalTrackLength = (doc) => doc.tracks.reduce((s, t) => s + dist(t.a, t.b), 0);
